<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XQTSCatalog.xsl" ?>
<!DOCTYPE test-suite [

<!ELEMENT GroupInfo ( title, description ) >

<!ELEMENT citation-spec ( description | note | spec-URI )* >
<!ATTLIST citation-spec name NMTOKEN #REQUIRED >

<!ELEMENT citations ( citation-spec+ ) >

<!ELEMENT collection ( description, input-document+ ) >
<!ATTLIST collection Creator CDATA #REQUIRED >
<!ATTLIST collection ID NMTOKEN #REQUIRED >

<!ELEMENT comparison ( description ) >
<!ATTLIST comparison name NMTOKEN #REQUIRED >

<!ELEMENT comparisons ( comparison+ ) >

<!ELEMENT context-properties ( context-property+ ) >

<!ELEMENT context-property EMPTY >
<!ATTLIST context-property context-type ( dynamic | static ) #REQUIRED >
<!ATTLIST context-property name CDATA #REQUIRED >

<!ELEMENT contextItem ( #PCDATA ) >
<!ATTLIST contextItem role NMTOKEN #FIXED "principal-data" >

<!ELEMENT defaultCollection ( #PCDATA ) >
<!ATTLIST defaultCollection role NMTOKEN #REQUIRED >

<!ELEMENT description ( #PCDATA ) >
<!ATTLIST description last-mod NMTOKEN #IMPLIED >

<!ELEMENT expected-error ( #PCDATA ) >
<!ATTLIST expected-error input-document NMTOKEN #IMPLIED >
<!ATTLIST expected-error spec-version NMTOKENS #IMPLIED >

<!ELEMENT feature EMPTY >
<!ATTLIST feature name CDATA #REQUIRED >

<!ELEMENT features ( feature+ ) >

<!ELEMENT implementation-defined-item ( description ) >
<!ATTLIST implementation-defined-item name ID #REQUIRED >
<!ATTLIST implementation-defined-item spec ( DataModel | FuncOps | Serialization | XQuery ) #REQUIRED >

<!ELEMENT implementation-defined-items ( implementation-defined-item+ ) >

<!ELEMENT input-URI ( #PCDATA ) >
<!ATTLIST input-URI role NMTOKEN #FIXED "principal-data" >
<!ATTLIST input-URI variable ( input-context | input-context1 | input-context2 ) #REQUIRED >

<!ELEMENT input-document ( #PCDATA ) >

<!ELEMENT input-file ( #PCDATA ) >
<!ATTLIST input-file role NMTOKEN #FIXED "principal-data" >
<!ATTLIST input-file variable ( input-context | input-context1 | input-context2 | input-context3 | inputDocument | var ) #REQUIRED >

<!ELEMENT input-query EMPTY >
<!ATTLIST input-query date CDATA #REQUIRED >
<!ATTLIST input-query name ID #REQUIRED >
<!ATTLIST input-query variable NMTOKEN #FIXED "x" >

<!ELEMENT module ( #PCDATA | description )* >
<!ATTLIST module Creator CDATA #IMPLIED >
<!ATTLIST module FileName CDATA #IMPLIED >
<!ATTLIST module ID ID #IMPLIED >
<!ATTLIST module namespace CDATA #IMPLIED >

<!ELEMENT note ( #PCDATA ) >

<!ELEMENT output-file ( #PCDATA ) >
<!ATTLIST output-file compare ( Fragment | Ignore | Inspect | Text | XML ) #REQUIRED >
<!ATTLIST output-file input-document NMTOKEN #IMPLIED >
<!ATTLIST output-file spec-version NMTOKENS #IMPLIED >
<!ATTLIST output-file role NMTOKEN #FIXED "principal" >

<!ELEMENT query ( description? ) >
<!ATTLIST query date CDATA #REQUIRED >
<!ATTLIST query name NMTOKEN #REQUIRED >
<!ATTLIST query static-name NMTOKEN #IMPLIED >

<!ELEMENT reflects-resolution ( #PCDATA ) >

<!ELEMENT role ( description, note? ) >
<!ATTLIST role name NMTOKEN #REQUIRED >

<!ELEMENT roles ( role+ ) >

<!ELEMENT scenario ( description ) >
<!ATTLIST scenario name NMTOKEN #REQUIRED >

<!ELEMENT scenarios ( scenario+ ) >

<!ELEMENT schema ( description ) >
<!ATTLIST schema FileName CDATA #REQUIRED >
<!ATTLIST schema ID ID #REQUIRED >
<!ATTLIST schema uri CDATA #REQUIRED >

<!ELEMENT source ( description, note* ) >
<!ATTLIST source Creator CDATA #REQUIRED >
<!ATTLIST source FileName CDATA #REQUIRED >
<!ATTLIST source ID ID #REQUIRED >
<!ATTLIST source schema NMTOKEN #IMPLIED >

<!ELEMENT sources ( source+, schema+, collection+, module+ ) >

<!ELEMENT spec-URI ( #PCDATA ) >

<!ELEMENT spec-citation EMPTY >
<!ATTLIST spec-citation section-number NMTOKEN #REQUIRED >
<!ATTLIST spec-citation section-pointer NMTOKEN #REQUIRED >
<!ATTLIST spec-citation section-title CDATA #REQUIRED >
<!ATTLIST spec-citation spec ( DataModel | FuncOps | UseCases | XQuery ) #REQUIRED >

<!ELEMENT test-case ( contextItem | defaultCollection | description | expected-error | input-URI | input-file | input-query | module | output-file | query | reflects-resolution | spec-citation )* >
<!ATTLIST test-case Creator CDATA #REQUIRED >
<!ATTLIST test-case FilePath CDATA #REQUIRED >
<!ATTLIST test-case is-XPath2 ( false | true ) #IMPLIED >
<!ATTLIST test-case name ID #REQUIRED >
<!ATTLIST test-case scenario ( parse-error | runtime-error | standard ) #REQUIRED >

<!ELEMENT test-group ( GroupInfo | test-case | test-group )* >
<!ATTLIST test-group featureOwner CDATA #IMPLIED >
<!ATTLIST test-group is-XPath2 ( false | true ) #IMPLIED >
<!ATTLIST test-group name ID #REQUIRED >
<!ATTLIST test-group xmlns CDATA #IMPLIED >

<!ELEMENT test-suite ( test-suite-info, citations, comparisons, roles, scenarios, sources, implementation-defined-items, features, context-properties, test-group+ ) >
<!ATTLIST test-suite CatalogDesignDate NMTOKEN #REQUIRED >
<!ATTLIST test-suite ResultOffsetPath CDATA #REQUIRED >
<!ATTLIST test-suite SourceOffsetPath CDATA #REQUIRED >
<!ATTLIST test-suite XQueryFileExtension NMTOKEN #REQUIRED >
<!ATTLIST test-suite XQueryQueryOffsetPath CDATA #REQUIRED >
<!ATTLIST test-suite XQueryXFileExtension NMTOKEN #REQUIRED >
<!ATTLIST test-suite XQueryXQueryOffsetPath CDATA #REQUIRED >
<!ATTLIST test-suite version CDATA #REQUIRED >
<!ATTLIST test-suite xmlns CDATA #REQUIRED >
<!ATTLIST test-suite xmlns:xsi CDATA #REQUIRED >
<!ATTLIST test-suite xsi:schemaLocation CDATA #REQUIRED >

<!ELEMENT test-suite-info ( title, description ) >

<!ELEMENT title ( #PCDATA ) >

<!ENTITY CombinedErrorCodes SYSTEM "cat/CombinedErrorCodes.xml">
<!ENTITY StaticContext SYSTEM "cat/StaticContext.xml">
<!ENTITY SequenceTypeSyntax SYSTEM "cat/SequenceTypeSyntax.xml">
<!ENTITY Literals SYSTEM "cat/Literals.xml">
<!ENTITY ParenExpr SYSTEM "cat/ParenExpr.xml">
<!ENTITY ExternalContextExpr SYSTEM "cat/ExternalContextExpr.xml">
<!ENTITY InternalContextExpr SYSTEM "cat/InternalContextExpr.xml">
<!ENTITY FunctionCallExpr SYSTEM "cat/FunctionCallExpr.xml">
<!ENTITY PathExpressions SYSTEM "cat/PathExpressions.xml">
<!ENTITY Steps SYSTEM "cat/Steps.xml">
<!ENTITY Axes SYSTEM "cat/Axes.xml">
<!ENTITY NodeTest SYSTEM "cat/NodeTest.xml">
<!ENTITY NameTest SYSTEM "cat/NameTest.xml">
<!ENTITY Predicates SYSTEM "cat/Predicates.xml">
<!ENTITY UnabbrAxes SYSTEM "cat/UnabbrAxes.xml">
<!ENTITY AbbrAxes SYSTEM "cat/AbbrAxes.xml">
<!ENTITY commaOp SYSTEM "cat/commaOp.xml">
<!ENTITY RangeExpr SYSTEM "cat/RangeExpr.xml">
<!ENTITY FilterExpr SYSTEM "cat/FilterExpr.xml">
<!ENTITY CombNodeSeq SYSTEM "cat/CombNodeSeq.xml">
<!ENTITY NumericAdd SYSTEM "cat/NumericAdd.xml">
<!ENTITY NumericSubtract SYSTEM "cat/NumericSubtract.xml">
<!ENTITY NumericMultiply SYSTEM "cat/NumericMultiply.xml">
<!ENTITY NumericDivide SYSTEM "cat/NumericDivide.xml">
<!ENTITY NumericIntegerDivide SYSTEM "cat/NumericIntegerDivide.xml">
<!ENTITY NumericMod SYSTEM "cat/NumericMod.xml">
<!ENTITY NumericUnaryPlus SYSTEM "cat/NumericUnaryPlus.xml">
<!ENTITY NumericUnaryMinus SYSTEM "cat/NumericUnaryMinus.xml">
<!ENTITY YearMonthDurationAdd SYSTEM "cat/YearMonthDurationAdd.xml">
<!ENTITY YearMonthDurationSubtract SYSTEM "cat/YearMonthDurationSubtract.xml">
<!ENTITY YearMonthDurationMultiply SYSTEM "cat/YearMonthDurationMultiply.xml">
<!ENTITY YearMonthDurationDivide SYSTEM "cat/YearMonthDurationDivide.xml">
<!ENTITY YearMonthDurationDivideYMD SYSTEM "cat/YearMonthDurationDivideYMD.xml">
<!ENTITY DayTimeDurationAdd SYSTEM "cat/DayTimeDurationAdd.xml">
<!ENTITY DayTimeDurationSubtract SYSTEM "cat/DayTimeDurationSubtract.xml">
<!ENTITY DayTimeDurationMultiply SYSTEM "cat/DayTimeDurationMultiply.xml">
<!ENTITY DayTimeDurationDivide SYSTEM "cat/DayTimeDurationDivide.xml">
<!ENTITY DayTimeDurationDivideDTD SYSTEM "cat/DayTimeDurationDivideDTD.xml">
<!ENTITY dateTimesSubtract SYSTEM "cat/dateTimesSubtract.xml">
<!ENTITY DatesSubtract SYSTEM "cat/DatesSubtract.xml">
<!ENTITY TimeSubtract SYSTEM "cat/TimeSubtract.xml">
<!ENTITY YearMonthDurationAddDT SYSTEM "cat/YearMonthDurationAddDT.xml">
<!ENTITY DateTimeAddDTD SYSTEM "cat/DateTimeAddDTD.xml">
<!ENTITY DateTimeSubtractYMD SYSTEM "cat/DateTimeSubtractYMD.xml">
<!ENTITY DateTimeSubtractDTD SYSTEM "cat/DateTimeSubtractDTD.xml">
<!ENTITY DateAddYMD SYSTEM "cat/DateAddYMD.xml">
<!ENTITY DateAddDTD SYSTEM "cat/DateAddDTD.xml">
<!ENTITY DateSubtractYMD SYSTEM "cat/DateSubtractYMD.xml">
<!ENTITY DateSubtractDTD SYSTEM "cat/DateSubtractDTD.xml">
<!ENTITY TimeAddDTD SYSTEM "cat/TimeAddDTD.xml">
<!ENTITY TimeSubtractDTD SYSTEM "cat/TimeSubtractDTD.xml">
<!ENTITY NumericEqual SYSTEM "cat/NumericEqual.xml">
<!ENTITY NumericLT SYSTEM "cat/NumericLT.xml">
<!ENTITY NumericGT SYSTEM "cat/NumericGT.xml">
<!ENTITY BooleanEqual SYSTEM "cat/BooleanEqual.xml">
<!ENTITY BooleanLT SYSTEM "cat/BooleanLT.xml">
<!ENTITY BooleanGT SYSTEM "cat/BooleanGT.xml">
<!ENTITY YearMonthDurationLT SYSTEM "cat/YearMonthDurationLT.xml">
<!ENTITY YearMonthDurationGT SYSTEM "cat/YearMonthDurationGT.xml">
<!ENTITY DayTimeDurationLT SYSTEM "cat/DayTimeDurationLT.xml">
<!ENTITY DayTimeDurationGT SYSTEM "cat/DayTimeDurationGT.xml">
<!ENTITY DurationEQ SYSTEM "cat/DurationEQ.xml">
<!ENTITY DateTimeEQ SYSTEM "cat/DateTimeEQ.xml">
<!ENTITY DateTimeLT SYSTEM "cat/DateTimeLT.xml">
<!ENTITY DateTimeGT SYSTEM "cat/DateTimeGT.xml">
<!ENTITY DateEQ SYSTEM "cat/DateEQ.xml">
<!ENTITY DateLT SYSTEM "cat/DateLT.xml">
<!ENTITY DateGT SYSTEM "cat/DateGT.xml">
<!ENTITY TimeEQ SYSTEM "cat/TimeEQ.xml">
<!ENTITY TimeLT SYSTEM "cat/TimeLT.xml">
<!ENTITY TimeGT SYSTEM "cat/TimeGT.xml">
<!ENTITY gYearMonthEQ SYSTEM "cat/gYearMonthEQ.xml">
<!ENTITY gYearEQ SYSTEM "cat/gYearEQ.xml">
<!ENTITY gMonthDayEQ SYSTEM "cat/gMonthDayEQ.xml">
<!ENTITY gMonthEQ SYSTEM "cat/gMonthEQ.xml">
<!ENTITY gDayEQ SYSTEM "cat/gDayEQ.xml">
<!ENTITY YearMonthDurationEQ SYSTEM "cat/YearMonthDurationEQ.xml">
<!ENTITY DayTimeDurationEQ SYSTEM "cat/DayTimeDurationEQ.xml">
<!ENTITY QNameEQ SYSTEM "cat/QNameEQ.xml">
<!ENTITY PrefixFromQName SYSTEM "cat/PrefixFromQName.xml">
<!ENTITY HexBinaryEQ SYSTEM "cat/HexBinaryEQ.xml">
<!ENTITY Base64BinaryEQ SYSTEM "cat/Base64BinaryEQ.xml">
<!ENTITY ValCompTypeChecking SYSTEM "cat/ValCompTypeChecking.xml">
<!ENTITY StringEqual SYSTEM "cat/StringEqual.xml">
<!ENTITY StringGT SYSTEM "cat/StringGT.xml">
<!ENTITY StringLT SYSTEM "cat/StringLT.xml">
<!ENTITY AnyURIEqual SYSTEM "cat/AnyURIEqual.xml">
<!ENTITY AnyURILtGt SYSTEM "cat/AnyURILtGt.xml">
<!ENTITY AnyURILeGe SYSTEM "cat/AnyURILeGe.xml">
<!ENTITY GenCompEq SYSTEM "cat/GenCompEq.xml">
<!ENTITY GenCompNE SYSTEM "cat/GenCompNE.xml">
<!ENTITY GenCompLT SYSTEM "cat/GenCompLT.xml">
<!ENTITY GenCompLTEQ SYSTEM "cat/GenCompLTEQ.xml">
<!ENTITY GenCompGT SYSTEM "cat/GenCompGT.xml">
<!ENTITY GenCompGTEQ SYSTEM "cat/GenCompGTEQ.xml">
<!ENTITY NodeSame SYSTEM "cat/NodeSame.xml">
<!ENTITY NodeBefore SYSTEM "cat/NodeBefore.xml">
<!ENTITY NodeAfter SYSTEM "cat/NodeAfter.xml">
<!ENTITY SeqUnion SYSTEM "cat/SeqUnion.xml">
<!ENTITY SeqIntersect SYSTEM "cat/SeqIntersect.xml">
<!ENTITY SeqExcept SYSTEM "cat/SeqExcept.xml">
<!ENTITY LogicExpr SYSTEM "cat/LogicExpr.xml">
<!ENTITY DirectConElem SYSTEM "cat/DirectConElem.xml">
<!ENTITY DirectConElemXML SYSTEM "cat/XMLEdition.xml">
<!ENTITY DirectConElemAttr SYSTEM "cat/DirectConElemAttr.xml">
<!ENTITY DirectConElemNamespace SYSTEM "cat/DirectConElemNamespace.xml">
<!ENTITY DirectConElemContent SYSTEM "cat/DirectConElemContent.xml">
<!ENTITY DirectConElemWhitespace SYSTEM "cat/DirectConElemWhitespace.xml">
<!ENTITY DirectConOther SYSTEM "cat/DirectConOther.xml">
<!ENTITY ComputeConElem SYSTEM "cat/ComputeConElem.xml">
<!ENTITY ComputeConAttr SYSTEM "cat/ComputeConAttr.xml">
<!ENTITY ConDocNode SYSTEM "cat/ConDocNode.xml">
<!ENTITY ConText SYSTEM "cat/ConText.xml">
<!ENTITY ComputeConPI SYSTEM "cat/ComputeConPI.xml">
<!ENTITY ComputeConComment SYSTEM "cat/ComputeConComment.xml">
<!ENTITY ConInScopeNamespace SYSTEM "cat/ConInScopeNamespace.xml">
<!ENTITY ForExprWithout SYSTEM "cat/ForExprWithout.xml">
<!ENTITY ForExprWith SYSTEM "cat/ForExprWith.xml">
<!ENTITY ForExprPositionalVar SYSTEM "cat/ForExprPositionalVar.xml">
<!ENTITY LetExprWithout SYSTEM "cat/LetExprWithout.xml">
<!ENTITY LetExprWith SYSTEM "cat/LetExprWith.xml">
<!ENTITY WhereExpr SYSTEM "cat/WhereExpr.xml">
<!ENTITY OrderbyExprWith SYSTEM "cat/OrderbyExprWith.xml">
<!ENTITY OrderbyExprWithout SYSTEM "cat/OrderbyExprWithout.xml">
<!ENTITY ReturnExpr SYSTEM "cat/ReturnExpr.xml">
<!ENTITY OrderExpr SYSTEM "cat/OrderExpr.xml">
<!ENTITY CondExpr SYSTEM "cat/CondExpr.xml">
<!ENTITY QuantExprWithout SYSTEM "cat/QuantExprWithout.xml">
<!ENTITY QuantExprWith SYSTEM "cat/QuantExprWith.xml">
<!ENTITY SeqExprInstanceOf SYSTEM "cat/SeqExprInstanceOf.xml">
<!ENTITY sequenceExprTypeswitch SYSTEM "cat/sequenceExprTypeswitch.xml">
<!ENTITY SeqExprCastToDerived SYSTEM "cat/SeqExprCastToDerived.xml">
<!ENTITY SeqExprCastToDerivedParents SYSTEM "cat/SeqExprCastToDerivedParents.xml">
<!ENTITY SeqExprCastWithinBranch SYSTEM "cat/SeqExprCastWithinBranch.xml">
<!ENTITY SeqExprCast SYSTEM "cat/SeqExprCast.xml">
<!ENTITY SeqExprCastable SYSTEM "cat/SeqExprCastable.xml">
<!ENTITY SeqExprTreat SYSTEM "cat/SeqExprTreat.xml">
<!ENTITY VersionProlog SYSTEM "cat/VersionProlog.xml">
<!ENTITY BoundarySpaceProlog SYSTEM "cat/BoundarySpaceProlog.xml">
<!ENTITY CollationProlog SYSTEM "cat/CollationProlog.xml">
<!ENTITY CopyNamespacesProlog SYSTEM "cat/CopyNamespacesProlog.xml">
<!ENTITY BaseURIProlog SYSTEM "cat/BaseURIProlog.xml">
<!ENTITY ConstructionProlog SYSTEM "cat/ConstructionProlog.xml">
<!ENTITY DefaultNamespaceProlog SYSTEM "cat/DefaultNamespaceProlog.xml">
<!ENTITY DefaultOrderingProlog SYSTEM "cat/DefaultOrderingProlog.xml">
<!ENTITY EmptyOrderProlog SYSTEM "cat/EmptyOrderProlog.xml">
<!ENTITY NamespaceProlog SYSTEM "cat/NamespaceProlog.xml">
<!ENTITY ExternalVariablesWithout SYSTEM "cat/ExternalVariablesWithout.xml">
<!ENTITY ExternalVariablesWith SYSTEM "cat/ExternalVariablesWith.xml">
<!ENTITY InternalVariablesWithout SYSTEM "cat/InternalVariablesWithout.xml">
<!ENTITY InternalVariablesWith SYSTEM "cat/InternalVariablesWith.xml">
<!ENTITY FunctionProlog SYSTEM "cat/FunctionProlog.xml">
<!ENTITY OptionDeclarationProlog SYSTEM "cat/OptionDeclarationProlog.xml">
<!ENTITY XQueryComment SYSTEM "cat/XQueryComment.xml">
<!ENTITY ExtensionExpression SYSTEM "cat/ExtensionExpression.xml">
<!ENTITY NodeNameFunc SYSTEM "cat/NodeNameFunc.xml">
<!ENTITY NilledFunc SYSTEM "cat/NilledFunc.xml">
<!ENTITY StringFunc SYSTEM "cat/StringFunc.xml">
<!ENTITY DataFunc SYSTEM "cat/DataFunc.xml">
<!ENTITY BaseURIFunc SYSTEM "cat/BaseURIFunc.xml">
<!ENTITY StaticBaseURIFunc SYSTEM "cat/StaticBaseURIFunc.xml">
<!ENTITY DocumentURIFunc SYSTEM "cat/DocumentURIFunc.xml">
<!ENTITY ErrorFunc SYSTEM "cat/ErrorFunc.xml">
<!ENTITY ErrorsAndOptimization SYSTEM "cat/ErrorsAndOptimization.xml">
<!ENTITY TraceFunc SYSTEM "cat/TraceFunc.xml">
<!ENTITY DateTimeFunc SYSTEM "cat/DateTimeFunc.xml">
<!ENTITY ABSFunc SYSTEM "cat/ABSFunc.xml">
<!ENTITY CeilingFunc SYSTEM "cat/CeilingFunc.xml">
<!ENTITY FloorFunc SYSTEM "cat/FloorFunc.xml">
<!ENTITY RoundFunc SYSTEM "cat/RoundFunc.xml">
<!ENTITY RoundEvenFunc SYSTEM "cat/RoundEvenFunc.xml">
<!ENTITY CodepointToStringFunc SYSTEM "cat/CodepointToStringFunc.xml">
<!ENTITY StringToCodepointFunc SYSTEM "cat/StringToCodepointFunc.xml">
<!ENTITY CompareFunction SYSTEM "cat/CompareFunction.xml">
<!ENTITY CodepointEqual SYSTEM "cat/CodepointEqual.xml">
<!ENTITY CompareFunc SYSTEM "cat/compareFunc.xml">
<!ENTITY ConcatFunc SYSTEM "cat/ConcatFunc.xml">
<!ENTITY StringJoinFunc SYSTEM "cat/StringJoinFunc.xml">
<!ENTITY SubstringFunc SYSTEM "cat/SubstringFunc.xml">
<!ENTITY StringLengthFunc SYSTEM "cat/StringLengthFunc.xml">
<!ENTITY NormalizeSpaceFunc SYSTEM "cat/NormalizeSpaceFunc.xml">
<!ENTITY NormalizeUnicodeFunc SYSTEM "cat/NormalizeUnicodeFunc.xml">
<!ENTITY UpperCaseFunc SYSTEM "cat/UpperCaseFunc.xml">
<!ENTITY LowerCaseFunc SYSTEM "cat/LowerCaseFunc.xml">
<!ENTITY TranslateFunc SYSTEM "cat/TranslateFunc.xml">
<!ENTITY Surrogates SYSTEM "cat/Surrogates.xml">
<!ENTITY EncodeURIfunc SYSTEM "cat/EncodeURIfunc.xml">
<!ENTITY IRIToURIfunc SYSTEM "cat/IRIToURIfunc.xml">
<!ENTITY EscapeHTMLURIFunc SYSTEM "cat/EscapeHTMLURIFunc.xml">
<!ENTITY ContainsFunc SYSTEM "cat/ContainsFunc.xml">
<!ENTITY StartsWithFunc SYSTEM "cat/StartsWithFunc.xml">
<!ENTITY EndsWithFunc SYSTEM "cat/EndsWithFunc.xml">
<!ENTITY SubstringBeforeFunc SYSTEM "cat/SubstringBeforeFunc.xml">
<!ENTITY SubstringAfterFunc SYSTEM "cat/SubstringAfterFunc.xml">
<!ENTITY MatchesFunc SYSTEM "cat/MatchesFunc.xml">
<!ENTITY ReplaceFunc SYSTEM "cat/ReplaceFunc.xml">
<!ENTITY TokenizeFunc SYSTEM "cat/TokenizeFunc.xml">
<!ENTITY AnalyzeString SYSTEM "cat/AnalyzeString.xml">
<!ENTITY ResolveURIFunc SYSTEM "cat/ResolveURIFunc.xml">
<!ENTITY TrueFunc SYSTEM "cat/TrueFunc.xml">
<!ENTITY FalseFunc SYSTEM "cat/FalseFunc.xml">
<!ENTITY NotFunc SYSTEM "cat/NotFunc.xml">
<!ENTITY YearsFromDurationFunc SYSTEM "cat/YearsFromDurationFunc.xml">
<!ENTITY MonthsFromDurationFunc SYSTEM "cat/MonthsFromDurationFunc.xml">
<!ENTITY DaysFromDurationFunc SYSTEM "cat/DaysFromDurationFunc.xml">
<!ENTITY HoursFromDurationFunc SYSTEM "cat/HoursFromDurationFunc.xml">
<!ENTITY MinutesFromDurationFunc SYSTEM "cat/MinutesFromDurationFunc.xml">
<!ENTITY SecondsFromDurationFunc SYSTEM "cat/SecondsFromDurationFunc.xml">
<!ENTITY YearFromDateTimeFunc SYSTEM "cat/YearFromDateTimeFunc.xml">
<!ENTITY MonthFromDateTimeFunc SYSTEM "cat/MonthFromDateTimeFunc.xml">
<!ENTITY DayFromDateTimeFunc SYSTEM "cat/DayFromDateTimeFunc.xml">
<!ENTITY HoursFromDateTimeFunc SYSTEM "cat/HoursFromDateTimeFunc.xml">
<!ENTITY MinutesFromDateTimeFunc SYSTEM "cat/MinutesFromDateTimeFunc.xml">
<!ENTITY SecondsFromDateTimeFunc SYSTEM "cat/SecondsFromDateTimeFunc.xml">
<!ENTITY TimezoneFromDateTimeFunc SYSTEM "cat/TimezoneFromDateTimeFunc.xml">
<!ENTITY YearFromDateFunc SYSTEM "cat/YearFromDateFunc.xml">
<!ENTITY MonthFromDateFunc SYSTEM "cat/MonthFromDateFunc.xml">
<!ENTITY DayFromDateFunc SYSTEM "cat/DayFromDateFunc.xml">
<!ENTITY TimezoneFromDateFunc SYSTEM "cat/TimezoneFromDateFunc.xml">
<!ENTITY HoursFromTimeFunc SYSTEM "cat/HoursFromTimeFunc.xml">
<!ENTITY MinutesFromTimeFunc SYSTEM "cat/MinutesFromTimeFunc.xml">
<!ENTITY SecondsFromTimeFunc SYSTEM "cat/SecondsFromTimeFunc.xml">
<!ENTITY TimezoneFromTimeFunc SYSTEM "cat/TimezoneFromTimeFunc.xml">
<!ENTITY AdjDateTimeToTimezoneFunc SYSTEM "cat/AdjDateTimeToTimezoneFunc.xml">
<!ENTITY AdjDateToTimezoneFunc SYSTEM "cat/AdjDateToTimezoneFunc.xml">
<!ENTITY AdjTimeToTimezoneFunc SYSTEM "cat/AdjTimeToTimezoneFunc.xml">
<!ENTITY ResolveQNameConstructFunc SYSTEM "cat/ResolveQNameConstructFunc.xml">
<!ENTITY ExpandedQNameConstructFunc SYSTEM "cat/ExpandedQNameConstructFunc.xml">
<!ENTITY LocalNameFromQNameFunc SYSTEM "cat/LocalNameFromQNameFunc.xml">
<!ENTITY NamespaceURIFromQNameFunc SYSTEM "cat/NamespaceURIFromQNameFunc.xml">
<!ENTITY NamespaceURIForPrefixFunc SYSTEM "cat/NamespaceURIForPrefixFunc.xml">
<!ENTITY InScopePrefixesFunc SYSTEM "cat/InScopePrefixesFunc.xml">
<!ENTITY NameFunc SYSTEM "cat/NameFunc.xml">
<!ENTITY NodeLocalNameFunc SYSTEM "cat/NodeLocalNameFunc.xml">
<!ENTITY NodeNamespaceURIFunc SYSTEM "cat/NodeNamespaceURIFunc.xml">
<!ENTITY NodeNumberFunc SYSTEM "cat/NodeNumberFunc.xml">
<!ENTITY NodeLangFunc SYSTEM "cat/NodeLangFunc.xml">
<!ENTITY NodeRootFunc SYSTEM "cat/NodeRootFunc.xml">
<!ENTITY SeqBooleanFunc SYSTEM "cat/SeqBooleanFunc.xml">
<!ENTITY SeqIndexOfFunc SYSTEM "cat/SeqIndexOfFunc.xml">
<!ENTITY SeqEmptyFunc SYSTEM "cat/SeqEmptyFunc.xml">
<!ENTITY SeqExistsFunc SYSTEM "cat/SeqExistsFunc.xml">
<!ENTITY SeqDistinctValuesFunc SYSTEM "cat/SeqDistinctValuesFunc.xml">
<!ENTITY SeqInsertBeforeFunc SYSTEM "cat/SeqInsertBeforeFunc.xml">
<!ENTITY SeqRemoveFunc SYSTEM "cat/SeqRemoveFunc.xml">
<!ENTITY SeqReverseFunc SYSTEM "cat/SeqReverseFunc.xml">
<!ENTITY SeqSubsequenceFunc SYSTEM "cat/SeqSubsequenceFunc.xml">
<!ENTITY SeqUnorderedFunc SYSTEM "cat/SeqUnorderedFunc.xml">
<!ENTITY SeqZeroOrOneFunc SYSTEM "cat/SeqZeroOrOneFunc.xml">
<!ENTITY SeqOneOrMoreFunc SYSTEM "cat/SeqOneOrMoreFunc.xml">
<!ENTITY SeqExactlyOneFunc SYSTEM "cat/SeqExactlyOneFunc.xml">
<!ENTITY SeqDeepEqualFunc SYSTEM "cat/SeqDeepEqualFunc.xml">
<!ENTITY SeqCountFunc SYSTEM "cat/SeqCountFunc.xml">
<!ENTITY SeqAVGFunc SYSTEM "cat/SeqAVGFunc.xml">
<!ENTITY SeqMAXFunc SYSTEM "cat/SeqMAXFunc.xml">
<!ENTITY SeqMINFunc SYSTEM "cat/SeqMINFunc.xml">
<!ENTITY SeqSUMFunc SYSTEM "cat/SeqSUMFunc.xml">
<!ENTITY SeqIDFunc SYSTEM "cat/SeqIDFunc.xml">
<!ENTITY SeqIDREFFunc SYSTEM "cat/SeqIDREFFunc.xml">
<!ENTITY SeqDocAvailableFunc SYSTEM "cat/SeqDocAvailableFunc.xml">
<!ENTITY SeqDocFunc SYSTEM "cat/SeqDocFunc.xml">
<!ENTITY SeqCollectionFunc SYSTEM "cat/SeqCollectionFunc.xml">
<!ENTITY ContextPositionFunc SYSTEM "cat/ContextPositionFunc.xml">
<!ENTITY ContextLastFunc SYSTEM "cat/ContextLastFunc.xml">
<!ENTITY ContextCurrentDatetimeFunc SYSTEM "cat/ContextCurrentDatetimeFunc.xml">
<!ENTITY ContextCurrentDateFunc SYSTEM "cat/ContextCurrentDateFunc.xml">
<!ENTITY ContextCurrentTimeFunc SYSTEM "cat/ContextCurrentTimeFunc.xml">
<!ENTITY ContextDefaultCollationFunc SYSTEM "cat/ContextDefaultCollationFunc.xml">
<!ENTITY ContextImplicitTimezoneFunc SYSTEM "cat/ContextImplicitTimezoneFunc.xml">
<!ENTITY FLWORExprSI SYSTEM "cat/FLWORExprSI.xml">
<!ENTITY ConstructSI SYSTEM "cat/ConstructSI.xml">
<!ENTITY versionPrologSI SYSTEM "cat/versionPrologSI.xml">
<!ENTITY MiscFunctions SYSTEM "cat/MiscFunctions.xml">
<!ENTITY ElementWithId SYSTEM "cat/ElementWithId.xml">
<!ENTITY SeqExprCastSI SYSTEM "cat/SeqExprCastSI.xml">
<!ENTITY NumericEqualSI SYSTEM "cat/NumericEqualSI.xml">
<!ENTITY NotationEQSI SYSTEM "cat/NotationEQSI.xml">
<!ENTITY UserDefinedSI SYSTEM "cat/UserDefinedSI.xml">
<!ENTITY SchemaImportProlog SYSTEM "cat/SchemaImportProlog.xml">
<!ENTITY ForExprTypeSI SYSTEM "cat/ForExprTypeSI.xml">
<!ENTITY PathExprSI SYSTEM "cat/PathExprSI.xml">
<!ENTITY ValidateExpression SYSTEM "cat/ValidateExpression.xml">
<!ENTITY STAxes SYSTEM "cat/STAxes.xml">
<!ENTITY STFLWORExpr SYSTEM "cat/STFLWORExpr.xml">
<!ENTITY STFunctions SYSTEM "cat/STFunctions.xml">
<!ENTITY ancestorAxis SYSTEM "cat/ancestorAxis.xml">
<!ENTITY ancestor-or-selfAxis SYSTEM "cat/ancestor-or-selfAxis.xml">
<!ENTITY followingAxis SYSTEM "cat/followingAxis.xml">
<!ENTITY following-siblingAxis SYSTEM "cat/following-siblingAxis.xml">
<!ENTITY precedingAxis SYSTEM "cat/precedingAxis.xml">
<!ENTITY preceding-siblingAxis SYSTEM "cat/preceding-siblingAxis.xml">
<!ENTITY ModuleImport SYSTEM "cat/ModuleImport.xml">
<!ENTITY ModuleProlog SYSTEM "cat/ModuleProlog.xml">
<!ENTITY Serialization SYSTEM "cat/Serialization.xml">
<!ENTITY Appendix-A4 SYSTEM "cat/Appendix-A4.xml">
<!ENTITY Annex-E SYSTEM "cat/Annex-E.xml">
<!ENTITY UseCaseXMP SYSTEM "cat/UseCaseXMP.xml">
<!ENTITY UseCaseTREE SYSTEM "cat/UseCaseTREE.xml">
<!ENTITY UseCaseSEQ SYSTEM "cat/UseCaseSEQ.xml">
<!ENTITY UseCaseR SYSTEM "cat/UseCaseR.xml">
<!ENTITY UseCaseSGML SYSTEM "cat/UseCaseSGML.xml">
<!ENTITY UseCaseSTRING SYSTEM "cat/UseCaseSTRING.xml">
<!ENTITY UseCaseNS SYSTEM "cat/UseCaseNS.xml">
<!ENTITY UseCasePARTS SYSTEM "cat/UseCasePARTS.xml">
<!ENTITY XMark SYSTEM "cat/XMark.xml">
<!ENTITY functx-fn-abs SYSTEM "cat/functx-fn-abs.xml">
<!ENTITY functx-fn-adjust-dateTime-to-timezone SYSTEM "cat/functx-fn-adjust-dateTime-to-timezone.xml">
<!ENTITY functx-fn-adjust-date-to-timezone SYSTEM "cat/functx-fn-adjust-date-to-timezone.xml">
<!ENTITY functx-fn-adjust-time-to-timezone SYSTEM "cat/functx-fn-adjust-time-to-timezone.xml">
<!ENTITY functx-fn-avg SYSTEM "cat/functx-fn-avg.xml">
<!ENTITY functx-fn-base-uri SYSTEM "cat/functx-fn-base-uri.xml">
<!ENTITY functx-fn-boolean SYSTEM "cat/functx-fn-boolean.xml">
<!ENTITY functx-fn-ceiling SYSTEM "cat/functx-fn-ceiling.xml">
<!ENTITY functx-fn-codepoint-equal SYSTEM "cat/functx-fn-codepoint-equal.xml">
<!ENTITY functx-fn-codepoints-to-string SYSTEM "cat/functx-fn-codepoints-to-string.xml">
<!ENTITY functx-fn-compare SYSTEM "cat/functx-fn-compare.xml">
<!ENTITY functx-fn-concat SYSTEM "cat/functx-fn-concat.xml">
<!ENTITY functx-fn-contains SYSTEM "cat/functx-fn-contains.xml">
<!ENTITY functx-fn-count SYSTEM "cat/functx-fn-count.xml">
<!ENTITY functx-fn-data SYSTEM "cat/functx-fn-data.xml">
<!ENTITY functx-fn-dateTime SYSTEM "cat/functx-fn-dateTime.xml">
<!ENTITY functx-fn-day-from-dateTime SYSTEM "cat/functx-fn-day-from-dateTime.xml">
<!ENTITY functx-fn-day-from-date SYSTEM "cat/functx-fn-day-from-date.xml">
<!ENTITY functx-fn-days-from-duration SYSTEM "cat/functx-fn-days-from-duration.xml">
<!ENTITY functx-fn-deep-equal SYSTEM "cat/functx-fn-deep-equal.xml">
<!ENTITY functx-fn-default-collation SYSTEM "cat/functx-fn-default-collation.xml">
<!ENTITY functx-fn-distinct-values SYSTEM "cat/functx-fn-distinct-values.xml">
<!ENTITY functx-fn-doc-available SYSTEM "cat/functx-fn-doc-available.xml">
<!ENTITY functx-fn-empty SYSTEM "cat/functx-fn-empty.xml">
<!ENTITY functx-fn-encode-for-uri SYSTEM "cat/functx-fn-encode-for-uri.xml">
<!ENTITY functx-fn-ends-with SYSTEM "cat/functx-fn-ends-with.xml">
<!ENTITY functx-fn-escape-html-uri SYSTEM "cat/functx-fn-escape-html-uri.xml">
<!ENTITY functx-fn-exactly-one SYSTEM "cat/functx-fn-exactly-one.xml">
<!ENTITY functx-fn-exists SYSTEM "cat/functx-fn-exists.xml">
<!ENTITY functx-fn-false SYSTEM "cat/functx-fn-false.xml">
<!ENTITY functx-fn-floor SYSTEM "cat/functx-fn-floor.xml">
<!ENTITY functx-fn-hours-from-dateTime SYSTEM "cat/functx-fn-hours-from-dateTime.xml">
<!ENTITY functx-fn-hours-from-duration SYSTEM "cat/functx-fn-hours-from-duration.xml">
<!ENTITY functx-fn-hours-from-time SYSTEM "cat/functx-fn-hours-from-time.xml">
<!ENTITY functx-fn-index-of SYSTEM "cat/functx-fn-index-of.xml">
<!ENTITY functx-fn-insert-before SYSTEM "cat/functx-fn-insert-before.xml">
<!ENTITY functx-fn-iri-to-uri SYSTEM "cat/functx-fn-iri-to-uri.xml">
<!ENTITY functx-fn-lang SYSTEM "cat/functx-fn-lang.xml">
<!ENTITY functx-fn-last SYSTEM "cat/functx-fn-last.xml">
<!ENTITY functx-fn-local-name-from-QName SYSTEM "cat/functx-fn-local-name-from-QName.xml">
<!ENTITY functx-fn-local-name SYSTEM "cat/functx-fn-local-name.xml">
<!ENTITY functx-fn-lower-case SYSTEM "cat/functx-fn-lower-case.xml">
<!ENTITY functx-fn-matches SYSTEM "cat/functx-fn-matches.xml">
<!ENTITY functx-fn-max SYSTEM "cat/functx-fn-max.xml">
<!ENTITY functx-fn-minutes-from-dateTime SYSTEM "cat/functx-fn-minutes-from-dateTime.xml">
<!ENTITY functx-fn-minutes-from-duration SYSTEM "cat/functx-fn-minutes-from-duration.xml">
<!ENTITY functx-fn-minutes-from-time SYSTEM "cat/functx-fn-minutes-from-time.xml">
<!ENTITY functx-fn-min SYSTEM "cat/functx-fn-min.xml">
<!ENTITY functx-fn-month-from-dateTime SYSTEM "cat/functx-fn-month-from-dateTime.xml">
<!ENTITY functx-fn-month-from-date SYSTEM "cat/functx-fn-month-from-date.xml">
<!ENTITY functx-fn-months-from-duration SYSTEM "cat/functx-fn-months-from-duration.xml">
<!ENTITY functx-fn-namespace-uri-for-prefix SYSTEM "cat/functx-fn-namespace-uri-for-prefix.xml">
<!ENTITY functx-fn-namespace-uri-from-QName SYSTEM "cat/functx-fn-namespace-uri-from-QName.xml">
<!ENTITY functx-fn-namespace-uri SYSTEM "cat/functx-fn-namespace-uri.xml">
<!ENTITY functx-fn-name SYSTEM "cat/functx-fn-name.xml">
<!ENTITY functx-fn-nilled SYSTEM "cat/functx-fn-nilled.xml">
<!ENTITY functx-fn-node-name SYSTEM "cat/functx-fn-node-name.xml">
<!ENTITY functx-fn-normalize-space SYSTEM "cat/functx-fn-normalize-space.xml">
<!ENTITY functx-fn-normalize-unicode SYSTEM "cat/functx-fn-normalize-unicode.xml">
<!ENTITY functx-fn-not SYSTEM "cat/functx-fn-not.xml">
<!ENTITY functx-fn-number SYSTEM "cat/functx-fn-number.xml">
<!ENTITY functx-fn-one-or-more SYSTEM "cat/functx-fn-one-or-more.xml">
<!ENTITY functx-fn-position SYSTEM "cat/functx-fn-position.xml">
<!ENTITY functx-fn-prefix-from-QName SYSTEM "cat/functx-fn-prefix-from-QName.xml">
<!ENTITY functx-fn-QName SYSTEM "cat/functx-fn-QName.xml">
<!ENTITY functx-fn-remove SYSTEM "cat/functx-fn-remove.xml">
<!ENTITY functx-fn-replace SYSTEM "cat/functx-fn-replace.xml">
<!ENTITY functx-fn-resolve-QName SYSTEM "cat/functx-fn-resolve-QName.xml">
<!ENTITY functx-fn-resolve-uri SYSTEM "cat/functx-fn-resolve-uri.xml">
<!ENTITY functx-fn-reverse SYSTEM "cat/functx-fn-reverse.xml">
<!ENTITY functx-fn-root SYSTEM "cat/functx-fn-root.xml">
<!ENTITY functx-fn-round-half-to-even SYSTEM "cat/functx-fn-round-half-to-even.xml">
<!ENTITY functx-fn-round SYSTEM "cat/functx-fn-round.xml">
<!ENTITY functx-fn-seconds-from-dateTime SYSTEM "cat/functx-fn-seconds-from-dateTime.xml">
<!ENTITY functx-fn-seconds-from-duration SYSTEM "cat/functx-fn-seconds-from-duration.xml">
<!ENTITY functx-fn-seconds-from-time SYSTEM "cat/functx-fn-seconds-from-time.xml">
<!ENTITY functx-fn-starts-with SYSTEM "cat/functx-fn-starts-with.xml">
<!ENTITY functx-fn-string-join SYSTEM "cat/functx-fn-string-join.xml">
<!ENTITY functx-fn-string-length SYSTEM "cat/functx-fn-string-length.xml">
<!ENTITY functx-fn-string-to-codepoints SYSTEM "cat/functx-fn-string-to-codepoints.xml">
<!ENTITY functx-fn-string SYSTEM "cat/functx-fn-string.xml">
<!ENTITY functx-fn-subsequence SYSTEM "cat/functx-fn-subsequence.xml">
<!ENTITY functx-fn-substring-after SYSTEM "cat/functx-fn-substring-after.xml">
<!ENTITY functx-fn-substring-before SYSTEM "cat/functx-fn-substring-before.xml">
<!ENTITY functx-fn-substring SYSTEM "cat/functx-fn-substring.xml">
<!ENTITY functx-fn-sum SYSTEM "cat/functx-fn-sum.xml">
<!ENTITY functx-fn-timezone-from-dateTime SYSTEM "cat/functx-fn-timezone-from-dateTime.xml">
<!ENTITY functx-fn-timezone-from-date SYSTEM "cat/functx-fn-timezone-from-date.xml">
<!ENTITY functx-fn-timezone-from-time SYSTEM "cat/functx-fn-timezone-from-time.xml">
<!ENTITY functx-fn-tokenize SYSTEM "cat/functx-fn-tokenize.xml">
<!ENTITY functx-fn-translate SYSTEM "cat/functx-fn-translate.xml">
<!ENTITY functx-fn-true SYSTEM "cat/functx-fn-true.xml">